version: '2.4'

networks:
  boom_system:

services:
  tensorflow:
    container_name: tf_ai
    image: tensorflow/tensorflow:1.13.1-gpu-py3
    restart: always
    networks:
      - boom_system
    ports:
      - 8080:8080
    volumes:
      - /home/hamdi/Documents:/home

  pytorch:
    container_name: torch_ai
    image: pytorch/pytorch:latest
    restart: always
    networks:
      - boom_system
    ports:
      - 8081:8081
    volumes:
      - /home/hamdi/Documents:/home